export const data = {
  products: [
    {
      id: 1,
      name: "Free Shirt",
      slug: "free-shirt",
      category: "Shirts",
      image: "/images/p1.png",
      isFeatured: true,
      featuredImage: "/images/banner1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 2,
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/p2.png",
      isFeatured: true,
      featuredImage: "/images/banner2.jpg",
      price: 80,
      brand: "Adidas",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 3,
      name: "Slim Shirt",
      slug: "slim-shirt",
      category: "Shirts",
      image: "/images/p3.png",
      price: 90,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 4,
      name: "Golf Shirt",
      slug: "golf-shirt",
      category: "Shirts",
      image: "/images/p4.png",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "Smart looking shirt",
    },
    {
      id: 5,
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirts",
      image: "/images/p5.png",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      id: 6,
      name: "Classic Shirt",
      slug: "classic-shirt",
      category: "Shirts",
      image: "/images/p6.png",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
  ],
};
